### PR TITLE
i1684:constrain current_burden_estimate_set to not null

### PR DESCRIPTION
**Pull request by xiangli313**
Youtrack:
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1684

Task:
as titled.

### CODE REVIEW

**Comment by xiangli313** [comment]
Package testing pending - science is down at the moment.

**Comment by richfitz** [comment]
science should be all back up now

**Comment by xiangli313** [comment]
Two things:
1) Wes's touchstone fast-forward script is run on prod and uta, not on science, so the test failed on science
2) on prod, the test also failed, because of very minor rounding errors. For example
```
test-dalys.R:52: failure: dalys_calculation
`dat` has changed from known value recorded in 'jenner-test-data/dalys_calculation/PSU-Ferrari.rds'.
Component “value”: Mean relative difference: 9.48124e-07
```

**Comment by richfitz** [comment]
:point_up: Oh I'm sorry - I _was_ running against science...

**Comment by richfitz** [comment]
Now I see 

```
✔ | OK F W S | Context
✖ |  2 1     | dalys_calculation [8.6 s]
────────────────────────────────────────────────────────────────────────────────
test-dalys.R:52: failure: dalys_calculation
`dat` has changed from known value recorded in 'jenner-test-data/dalys_calculation/PSU-Ferrari.rds'.
Component “value”: Mean relative difference: 9.48124e-07
────────────────────────────────────────────────────────────────────────────────
✖ |  4 2     | impact_method2 [8.4 s]
────────────────────────────────────────────────────────────────────────────────
test-impact_method2.R:45: failure: impact_calculation, method1
`a` has changed from known value recorded in 'jenner-test-data/impact_calculation/method1.rds'.
Component “impact”: Mean relative difference: 1.764912e-06

test-impact_method2.R:180: failure: impact_calculation, method2-HepB-specific
`a` has changed from known value recorded in 'jenner-test-data/impact_calculation/method2-hepb.rds'.
Component “tot_rate”: Mean relative difference: 5.630581e-07
Component “impact”: Mean relative difference: 5.630581e-07
────────────────────────────────────────────────────────────────────────────────
✔ | 11       | util
```

**Comment by xiangli313** [comment]
Harvard Sweet has uploaded new estimates, so you will find the test failed again.

**Comment by xiangli313** [comment]
It was a bad decision to have Sweet in the test data. They have uploaded new estimates, but not as what we expect. I decide to use Mark Jit's instead.

**Comment by xiangli313** [comment]
Thanks, @richfitz. Has jenner been upgraded on science/prod machine as well?

**Comment by xiangli313** [comment]
I need to use the most recent Jenner for orderly reports.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
